version: "3.9"

services:
  kapachkin:
    image: ghcr.io/drdevil/discord-rust-bot:latest
    container_name: kapachkin
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    labels:
      - "diun.enable=true"
